### PR TITLE
Added iPad Pro support

### PR DESCRIPTION
**Pull request by CraigBeswetherick**
Added a spec file for the iPad Pro, and also updated https://github.com/gajus/scream/blob/cfde779a7730c0c9c31c18710dfb12989ca8a56e/src/scream.js#L139-L152

### CODE REVIEW

**Comment by gajus** [comment]
This looks great. Can you also add definition of iPad pro when zoomed?

**Comment by gajus** [comment]
See https://support.apple.com/en-gb/HT204390 if you are not familiar with Zoom view.

**Comment by CraigBeswetherick** [comment]
Sure, will do this now

**Comment by CraigBeswetherick** [comment]
Do you know of any tricks to enable Zoom within the emulator? 

"To enable Zoom, use three fingers and double-tap the screen."

**Comment by gajus** [comment]
It should be under: Settings -> Display & Brightness -> Display Zoom.

**Comment by CraigBeswetherick** [comment]
that option is hidden in the emulator

**Comment by gajus** [comment]
Maybe it is not available on iPad pro to begin with? I have used emulator to capture values for all other devices.

**Comment by CraigBeswetherick** [comment]
It was removed in xCode 6.0 apparently:

http://stackoverflow.com/questions/25977305/does-iphone-6-6-plus-simulator-supports-changing-of-display-zoom-mode

I can't really do anymore without a device it seems

**Comment by CraigBeswetherick** [comment]
Off to the shops....

**Comment by gajus** [comment]
Thank you for the PR. v2.1.1 has been published. I will capture the iPad Pro specs for zoomed in version when I am near Apple store.

**Comment by CraigBeswetherick** [comment]
Ah great, thank you! Does a version not need to be built so that it appears in the dist folder?

**Comment by gajus** [comment]
@CraigBeswetherick `./dist` was used only for browser (Bower) builds. I have removed those entirely and published ES6 version https://github.com/gajus/scream/blob/311b35c51541b264dbb1c0f2998d7ae4ac652f84/src/scream.js. There are primarily stylistic changes. Should not affect the code (or API).

**Pull request merged**
